on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: cn
    container: ccr.ccs.tencentyun.com/xiaoqidun/actbi:latest
    strategy:
      matrix:
        include:
          - dockerfile: DockerfileCN
            registry: ccr.ccs.tencentyun.com
            image: ccr.ccs.tencentyun.com/xiaoqidun/actbi:latest
          - dockerfile: DockerfileHK
            registry: hkccr.ccs.tencentyun.com
            image: hkccr.ccs.tencentyun.com/xiaoqidun/actbi:latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: docker setup
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            "env.http_proxy=${{ env.HTTP_PROXY }}"
            "env.https_proxy=${{ env.HTTPS_PROXY }}"
            "env.no_proxy=${{ env.NO_PROXY }}"
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      - name: docker build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          file: ${{ matrix.dockerfile }}
          tags: ${{ matrix.image }}